# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

networks:
  updatenetwork:

services:
  ca-update:
    image: hyperledger/fabric-ca:1.4.9
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-update-orderer
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_SIGNING_DEFAULT_EXPIRY=87600h
      - FABRIC_CA_SERVER_PROFILES_TLS_EXPIRY=87600h
      - FABRIC_CA_SERVER_PORT=10054
    ports:
      - "10054:10054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ../ca-config:/etc/hyperledger/fabric-ca-server
    container_name: ca-update
    networks:
      - updatenetwork